-- SQLITE CREATE TABLE STATEMENTS FOR ACCESS DATABASE CONVERSION
-- GENERATED FROM MC - COPY.ACCDB SCHEMA ANALYSIS

-- 1. PARAMETER NAMES LOOKUP TABLE
CREATE TABLE IF NOT EXISTS PAR_NAMES (
    PAR_ID INTEGER PRIMARY KEY,
    PAR_NAME TEXT NOT NULL
);

-- 2. PARAMETER LIST - VALUES FOR EACH MODEL RUN
CREATE TABLE IF NOT EXISTS PAR_LIST (
    RUN_ID INTEGER NOT NULL,
    PAR_ID INTEGER NOT NULL,
    TEXT_VALUE TEXT,
    NUMERIC_VALUE REAL,
    PRIMARY KEY (RUN_ID, PAR_ID),
    FOREIGN KEY (PAR_ID) REFERENCES PAR_NAMES(PAR_ID)
);

-- 3. SORTED PARAMETERS FOR ANALYSIS
CREATE TABLE IF NOT EXISTS SORTED_PARAMETERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RUN_ID INTEGER NOT NULL,
    PAR_ID INTEGER NOT NULL,
    PARAMETER_VALUE REAL,
    FOREIGN KEY (PAR_ID) REFERENCES PAR_NAMES(PAR_ID)
);

-- 4. MODEL SIMULATION RESULTS
CREATE TABLE IF NOT EXISTS RESULTS (
    RUN INTEGER NOT NULL,
    ROW_NUMBER INTEGER NOT NULL,
    REACH TEXT,
    TERRESTRIAL_INPUT REAL,
    FLOW REAL,
    DATE_STAMP DATETIME DEFAULT (DATETIME('NOW')),
    PRIMARY KEY (RUN, ROW_NUMBER)
);

-- 5. STATISTICAL COEFFICIENTS AND PERFORMANCE METRICS
CREATE TABLE IF NOT EXISTS COEFFICIENTS (
    RUN INTEGER NOT NULL,
    ROW_NUMBER INTEGER NOT NULL,
    REACH TEXT,
    PARAMETER TEXT,
    R2 REAL,
    NS REAL,
    LOG_NS REAL,
    RMSE REAL,
    RE REAL,
    AD REAL,
    VAR REAL,
    N REAL,
    N_RE REAL,
    SS REAL,
    LOG_SS REAL,
    DATE_STAMP DATETIME DEFAULT (DATETIME('NOW')),
    PRIMARY KEY (RUN, ROW_NUMBER, REACH, PARAMETER)
);

-- 6. COEFFICIENT WEIGHTS FOR ANALYSIS
CREATE TABLE IF NOT EXISTS COEFFICIENT_WEIGHTS (
    COEFFICIENT_NAME TEXT PRIMARY KEY,
    COEFFICIENT_WEIGHT REAL NOT NULL
);

-- 7. INCA MODEL INPUT DATA
CREATE TABLE IF NOT EXISTS INCA_INPUTS (
    FILE_NAME TEXT NOT NULL,
    RUN INTEGER NOT NULL,
    ROW_NUMBER INTEGER NOT NULL,
    SMD REAL,
    HER REAL,
    T REAL,
    P REAL,
    DATE_STAMP DATETIME DEFAULT (DATETIME('NOW')),
    PRIMARY KEY (FILE_NAME, RUN, ROW_NUMBER)
);

-- 8. OBSERVED DATA FOR MODEL VALIDATION
CREATE TABLE IF NOT EXISTS OBSERVATIONS (
    REACH TEXT NOT NULL,
    PARAMETER TEXT NOT NULL,
    VALUE REAL,
    QC TEXT,
    DATE_STAMP DATETIME DEFAULT (DATETIME('NOW')),
    PRIMARY KEY (REACH, PARAMETER, DATE_STAMP)
);

-- 9. STATISTICAL ANALYSIS D-VALUES
CREATE TABLE IF NOT EXISTS D_VALUES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RANK INTEGER,
    PAR_NAME TEXT,
    PAR_ID INTEGER,
    X_RANGE REAL,
    D REAL,
    Z REAL,
    P REAL,
    ADJUSTED_P REAL,
    FOREIGN KEY (PAR_ID) REFERENCES PAR_NAMES(PAR_ID)
);

-- 10. PARAMETER SENSITIVITY SUMMARY
CREATE TABLE IF NOT EXISTS PARAMETER_SENSITIVITY_SUMMARY (
    PAR_NAME TEXT NOT NULL,
    PAR_ID INTEGER PRIMARY KEY,
    D REAL,
    MIN_OF_NUMERIC_VALUE REAL,
    MAX_OF_NUMERIC_VALUE REAL,
    X_RANGE REAL,
    Z REAL,
    P REAL,
    FOREIGN KEY (PAR_ID) REFERENCES PAR_NAMES(PAR_ID)
);

-- 11. REACH/LOCATION LOOKUP TABLE
CREATE TABLE IF NOT EXISTS REACH_ID (
    ID_CODE INTEGER PRIMARY KEY,
    REACH TEXT UNIQUE NOT NULL
);

-- CREATE INDEXES FOR BETTER PERFORMANCE
CREATE INDEX IF NOT EXISTS IDX_PAR_LIST_RUN_ID ON PAR_LIST(RUN_ID);
CREATE INDEX IF NOT EXISTS IDX_PAR_LIST_PAR_ID ON PAR_LIST(PAR_ID);
CREATE INDEX IF NOT EXISTS IDX_SORTED_PARAMS_PAR_ID ON SORTED_PARAMETERS(PAR_ID);
CREATE INDEX IF NOT EXISTS IDX_SORTED_PARAMS_RUN_ID ON SORTED_PARAMETERS(RUN_ID);
CREATE INDEX IF NOT EXISTS IDX_RESULTS_RUN ON RESULTS(RUN);
CREATE INDEX IF NOT EXISTS IDX_RESULTS_REACH ON RESULTS(REACH);
CREATE INDEX IF NOT EXISTS IDX_COEFFICIENTS_RUN ON COEFFICIENTS(RUN);
CREATE INDEX IF NOT EXISTS IDX_COEFFICIENTS_REACH ON COEFFICIENTS(REACH);
CREATE INDEX IF NOT EXISTS IDX_INCA_INPUTS_RUN ON INCA_INPUTS(RUN);
CREATE INDEX IF NOT EXISTS IDX_OBSERVATIONS_REACH ON OBSERVATIONS(REACH);
CREATE INDEX IF NOT EXISTS IDX_D_VALUES_PAR_ID ON D_VALUES(PAR_ID);

-- ENABLE FOREIGN KEY CONSTRAINTS
PRAGMA FOREIGN_KEYS = ON;